Repository pluginsGLPI/datainjection, pull requests merged in 2025-02, with the labels that each got.

#457 Fix(Core): escape data when check if already exist
  CHANGELOG.md
  inc/commoninjectionlib.class.php
Labels: bug

#458 Fix: Replace multiline_text fields when prefixed with #replace
  CHANGELOG.md
  hook.php
  inc/commoninjectionlib.class.php
  inc/engine.class.php
  inc/model.class.php
Labels: enhancement

#459 Chore(i18n): update translations
  locales/cs_CZ.po
  locales/datainjection.pot
  locales/en_GB.mo
  locales/en_GB.po
  locales/es_AR.po
  locales/es_EC.po
  locales/fi_FI.po
  locales/fr_FR.po
  locales/hr_HR.po
  locales/it_IT.po
  locales/ja_JP.po
  locales/ko_KR.po
  locales/pt_BR.po
  locales/pt_PT.po
  locales/ru_RU.po
  locales/sk_SK.po
  locales/tr_TR.mo
  locales/tr_TR.po
Labels: i18n
